project_id = "tyovnvuluyosjnabrzjc"

[functions.ai-dashboard-generator]
verify_jwt = true

[functions.approve-pending-registration]
verify_jwt = true

[functions.approve-reassignment-request]
verify_jwt = true

[functions.import-members]
verify_jwt = true

[functions.organization-emails]
verify_jwt = true

[functions.resend-invoice]
verify_jwt = true

[functions.send-invoice]
verify_jwt = true

[functions.send-overdue-reminder]
verify_jwt = true

[functions.test-email]
verify_jwt = true

[functions.track-invoice-open]
verify_jwt = false

[functions.create-external-user]
verify_jwt = false