project_id = "tyovnvuluyosjnabrzjc"

[functions.ai-dashboard-generator]
verify_jwt = true

[functions.import-members]
verify_jwt = true

[functions.organization-emails]
verify_jwt = true

[functions.test-email]
verify_jwt = true